language: node_js
script: play-${PLAY_VERSION}/play coveralls
node_js:
- 0.1
env: 
- PLAY_VERSION=2.2.3
before_script: 
- wget http://apt.typesafe.com/repo-deb-build-0002.deb
- sudo sh -c 'dpkg -i repo-deb-build-0002.deb'
- sudo apt-get update
- sudo apt-get install sbt
- wget http://downloads.typesafe.com/play/2.2.3/play-2.2.3.zip
- unzip -q play-${PLAY_VERSION}.zip
before_deploy:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
notifications:
  email:
    on_success: never
    on_failure: change
cache:
  directories:
  - $HOME/.ivy2
