language: node_js
script: play-${PLAY_VERSION}/play coveralls
node_js:
- 0.1
env: 
- PLAY_VERSION=2.2.3
before_script: 
- wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
- unzip -q play-${PLAY_VERSION}.zip
before_deploy:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
notifications:
  email:
    on_success: never
    on_failure: change
cache:
  directories:
  - $HOME/.ivy2
