language: node_js
script: play coveralls && npm test && ./upload_junitreport.sh
node_js:
- 0.1
env:
- PLAY_VERSION=2.2.3
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
- unzip -q play-${PLAY_VERSION}.zip
- export PATH=$PATH:$PWD/play-${PLAY_VERSION}/
before_deploy:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
notifications:
  email:
    on_success: never
    on_failure: change
cache:
  directories:
  - $HOME/.ivy2
deploy:
  provider: heroku
  app: bana
  strategy: git
  api_key:
    secure: gjO1rAOf8UXbWPWwknD7DTXl2dtVPHusPZkL3UMQ++PepxC+5lRAqOOAErHpH99Vj3g68cb9txKeFCKYb11Z4OGdxov3yB75TMNBs9e91nCft+dVhCvtTG5yWMrpGhkhG6CcOrT4OmVz5OxuLwctuoxPolOHFOHI8Iu8ap44U14=
