language: scala
script: play-${PLAY_VERSION}/play coveralls
env: 
- PLAY_VERSION=2.2.3
before_script: 
- wget http://downloads.typesafe.com/play/2.2.3/play-2.2.3.zip
- unzip -q play-${PLAY_VERSION}.zip
before_deploy:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
notifications:
  email:
    on_success: never
    on_failure: change
cache:
  directories:
  - $HOME/.ivy2
